[project]
name = "grapevne"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "packaging>=24.1",
]

[tool.uv]
dev-dependencies = [
    "nox>=2024.4.15",
    "pytest>=8.3.2",
    "ruff>=0.6.3",
]
